name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: microsoft

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod.jar
          path: ./build/libs/*.jar
          if-no-files-found: error
          compression-level: 0
